---
abstract: 'Mojolicious Plugin to create routes automatically'
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-INIConfig
no_index:
  directory:
    - t
    - inc
requires:
  Config::Tiny: 2.14
  Mojolicious: 3.84
version: 0.03
